### ISSUE TITLE
ffmpeg is not installed

### ISSUE THREAD

**Issue by azoth07** [oop7/YTSage#2]
just for win.exe

**Comment by oop7** [comment]
Could you explain your issue or provide me with more details?

**Comment by snowshoes** [comment]
Hello, thank you for creating such a wonderful tool!

I encounter the same error, at the very beginning I am not aware of the ffmpeg dependency, so the task failed with Error: 
`ERROR: You have requested merging of multiple formats but ffmpeg is not installed, Aborting due to --abort-on-error`.

Then I install ffmpeg under Windows10, and configure the path to make it work by running `ffmpeg -version` in Powershell, it shows the version info, apparently the ffmpeg was installed sucessfully,
 
however, when I reopen the YTSage, repeat the download process: analyze, download the highest resolution video, click download, then same error, could you please take a look at this issue ?

**Comment by snowshoes** [comment]
Sorry for the false positive, I remove then reinstall the executable, then everything works perfectly, thank you !
